# Generated by Django 2.1.5 on 2019-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
