# Generated by Django 2.1.5 on 2019-02-13 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=600)),
                ('created_by', models.CharField(max_length=100)),
                ('posted_by', models.CharField(max_length=100)),
            ],
        ),
    ]
