# Generated by Django 2.1.5 on 2019-02-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190213_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
