# Generated by Django 2.1.5 on 2019-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190213_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='foto',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
