# Generated by Django 2.1.5 on 2019-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190213_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='foto',
            field=models.ImageField(upload_to='blog/static/images'),
        ),
    ]
