# Generated by Django 2.1.7 on 2019-02-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190213_0834'),
        ('blog', '0006_auto_20190213_1010'),
    ]

    operations = [
    ]
