# Generated by Django 2.1.5 on 2019-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0002_mentee_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
